### ISSUE TITLE
install-iocage.sh

### ISSUE THREAD

**Issue by reelsense** [No9/vagrant-iocage#2]
I don't know what the philosophy of use is for this _Vagrantfile_. _But_ if the philosophy is _"A vagrant script install and configure iocage"_, then I would think pulling the latest bugs for _iocage_   from source would be a little too bleeding edge and difficult to maintain long term.

You can still get the _latest release_ binary from the FreeBSD repositories by switching `pkg` to fetch from **_latest_** instead of **_quarterly_**. I made a one-liner for that here: https://github.com/stationgroup/etc/tree/master/pkg/repos.

But if this _Vagrantfile_ is for testing the latest source then ignore me...

**Comment by No9** [comment]
Initially this script was for testing iocage latest as i was getting my head around it and features were landing fast at the time.

I find vagrant a handy way to document installs. I was hoping it could be used for the iocage CI but that issue is still open
https://github.com/iocage/iocage/issues/133

You have a good point though as I dont usually think of changing where pkg points to and im sure that will come in handy a5 some stage
Do you have any pointers on how/when things make it into LATEST?

**Comment by reelsense** [comment]
>Do you have any pointers on how/when things make it into LATEST?

I'm not sure about the _"How"_, but I think new [_releases_](https://github.com/iocage/iocage/releases) go to _[ports](https://www.freshports.org/sysutils/iocage/)_ first -> then the binary hits [_latest_](http://pkg.freebsd.org/FreeBSD:11:amd64/latest/) -> and eventually [_quarterly_](http://pkg.freebsd.org/FreeBSD:11:amd64/quarterly/).
